spring:
  liquibase:
    change-log: classpath*:/db/changelog/main.yml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
jwt:
  secret: jwt-secret
